class LevelManager():

	def __init__():
        self.levels = ["leap_of_faith"]
        self.levels.append("jumpering")
        self.levels.append("think_fast")
        self.levels.append("not_so_hard_maze")
        self.levels.append("one_jump")
        self.levels.append("ruins")
        self.levels.append("jumper")
        self.levels.append("nl10")
        self.levels.append("free_runner")
        self.levels.append("unknown")
        self.levels.append("nl9")
        self.levels.append("woah")
        self.levels.append("roof_climber")
        self.levels.append("zigzag")
        self.levels.append("nl7")
        self.levels.append("jump")
        self.levels.append("luck")
        self.levels.append("tower")
        self.levels.append("cheap_level")
        self.levels.append("just_an_other_level")
        self.levels.append("perhaps")
        self.levels.append("trial")
        self.levels.append("nl1")
        self.levels.append("nl6")
        self.levels.append("nl4")
        self.levels.append("spam")
        self.levels.append("nl3")
        self.levels.append("nl8")
        self.levels.append("bad_level")
        self.levels.append("frustration")
        self.levels.append("nl2")
        self.levels.append("pure_luck")
        self.levels.append("wild_guess")
        self.levels.append("nl5")
        self.levels.append("fly")